kind = "web"
previewPath = "/"
title = "VipGoPay"
version = "1.0.0"
id = "artifacts/vipgopay"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18263

[services.development]
run = "pnpm --filter @workspace/vipgopay run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/vipgopay", "run", "build" ]
publicDir = "artifacts/vipgopay/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18263"
BASE_PATH = "/"
